pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r assets favicon.png index.html sitemap.xml robots.txt public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
